# templated Dockfile transformed into useable Dockerfile
# by doing a global subsitution on strings
# $tag -- a container identifying tag
# $appname -- name of the pces app being built here
# $userargs -- empty if there are no user arguments, /tmp/extern/args/args-user otherwise
# 
# Usage:

# docker build -t $tag
# docker run -it --rm -v .:/tmp/extern $tag
#
FROM golang:1.23-bookworm

# Add whatever Debian packages you want here.
RUN apt-get -y update &&  \ 
    apt-get install --no-install-recommends -y \
    vim-nox && \
    rm -rf /var/lib/apt/lists/*

# Build the pcesapps app
WORKDIR /$appname
COPY . .
RUN $usermodules cd ./main && go mod tidy && go build -o /bin/sim main.go
CMD sim $userargs -is /tmp/extern/args/args-sim
