name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_TYPE: $(test "$GITHUB_REF_TYPE" = "tag" && echo xbeta || echo dev)
      IMAGE_TAG: $(test "$GITHUB_REF_TYPE" = "tag" && echo $GITHUB_REF_NAME)

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd beta && ./docker-build.sh $IMAGE_TYPE $IMAGE_TAG
