name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update image vars
      run: |
        if [ "$GITHUB_REF_TYPE" = "tag" ]
        then
          echo IMAGE_TYPE=""
          echo IMAGE_TAG=$GITHUB_REF_NAME
        else
          echo IMAGE_TYPE=-dev
          echo IMAGE_TAG=$(date -u +%s)
        fi >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: ./docker-build.sh $IMAGE_TYPE $IMAGE_TAG
      run: |
        TAG=ghcr.io/iti/pcesapps$IMAGE_TYPE:$IMAGE_TAG
        TAG2=ghcr.io/iti/pcesapps$IMAGE_TYPE:latest
        docker build --no-cache -t $TAG -t $TAG2 .
        docker push $TAG
        docker push $TAG2
